### ISSUE TITLE
CorrelationId not set when creating Child Logger

### ISSUE THREAD

**Issue by chrsch-dev** [SAP/cf-nodejs-logging-support#185]
Hi,

I discovered, that creating a new Child Logger doesn't work with the new version as before (v6).
Before I used the `createLogger()` function to create a new logger and got automatically the `correlation_id` property set ([code](https://github.com/SAP/cf-nodejs-logging-support/blob/c16436a1b252066d5c223895694fb3502c01683b/core/log-core.js#L620).

When doing the same with the current version of the library, the `correlation_id` is not set. Even calling the `setCorrelationId()` method of the logger doesn't work :(

**Comment by christiand93** [comment]
Hi Christian,

thank you for reaching out. I can confirm that the `correlation_id` field is not auto-generated nor settable for message logs written in the [global context](https://sap.github.io/cf-nodejs-logging-support/general-usage/logging-contexts#global-context). 

In general, context values are stored in a `RequestContext` object attached to a logger instance. The `RequestContext` is primarily responsible for storing request related context values, which is why it is not set for loggers in global context.

However, I agree that having a common `correlation_id` for log messages can be beneficial, even if the messages are not related to a specific request. My proposal would be to allow enabling context values for global context loggers. 
Enabling the context feature for a logger could be achieved by calling a dedicated method, e.g., `logger.enableContext()`, which would also process the context configuration (= generate a `correlation_id` on the fly).

Secondly, contexts should be inherited whenever `createLogger()` is called. This would also ensure that child loggers inherit request values, e.g., request_id, from their parent request logger (`req.logger`).

I will discuss this approach with my colleagues and provide a PR/update asap.

Kind regards,
Christian

**Comment by christiand93** [comment]
https://github.com/SAP/cf-nodejs-logging-support/pull/186 is merged, I will prepare a new release shortly.

**Comment by chrsch-dev** [comment]
Great, will check it after my vacation :)
