### ISSUE TITLE
Optional Color Coding

### ISSUE THREAD

**Issue by LukasMelzer** [SAP/cf-nodejs-logging-support#59]
Facilitating nodes `util.format` adds colors for different data types.
The respective ANSI codes work well with the most consoles but impair the readability of the messages when analyzed otherwise. This applies for exports but also for logging analyzers like the Elastic stack often used together with CloudFoundry.

Currently, the workaround would be stringifying all arguments given to a logger or removing the color codes afterwards.
To avoid this unnecessary processing, it would be beneficial to make the coloring optional or customizable.
This could easily be achieved by adding a function like:
```
var setColors(nodeUtilInspectStyles) {
    util.inspect.styles = nodeUtilInspectStyles;
}
```
or exposing the `styles` obejct directly.

**Comment by christiand93** [comment]
Hi,

changing `util.inspect.styles` does not affect the output of our library, since color coding is disabled by default independent of `util.inspect.styles`. However, if you pass already color coded strings to our library, these color codes will also be part of the logged message.

Kind regards,
Christian
