### ISSUE TITLE
Docu/hints for plain usage

### ISSUE THREAD

**Issue by WolfgangTheilmann** [SAP/cf-nodejs-logging-support#6]
Hi, probably a node.js newby question:
I would like to use your lib without any express nor winston library.
Could you please also information on how to do that?
Thanks, Wolfgang

**Comment by christiand93** [comment]
Hi Wolfgang,

winston is a necessary dependency of this library, since it provides the logging level logic and output transport system.

Using the library without express (or restify) should be possible, but will be limited to custom logs. If this your intention, we can provide an example soon.

If you want to log network activity from any other module than express or restify, it is necessary to implement and bind another specialized logger (like [log-express](https://github.com/SAP/cf-nodejs-logging-support/blob/master/cf-nodejs-logging-support-express/log-express.js) and [log-restify](https://github.com/SAP/cf-nodejs-logging-support/blob/master/cf-nodejs-logging-support-restify/log-restify.js)), which extracts request data.

Kind regards,
Christian

**Comment by WolfgangTheilmann** [comment]
Hi Christian,

thanks for the feedback; yes an example without express would be great.

Second, and along the line of what you call custom logs (in the sibling java project we distinguish between request logs and app logs): wouldn't it be also possible to create a request log "by hand", i.e. providing the relevant fields such as response time as explicit part of the log creation?

Cheers, Wolfgang

**Comment by christiand93** [comment]
Hi Wolfgang,

we have just implemented logging support for node.js [http module](https://nodejs.org/api/http.html), which is part of node.js. That includes request and custom logs. You can find an example in the documentation. 

Writing request logs by hand is possible, but our take on this library was to provide a clear and distinct api, and to make sure that every written log matches the logging schema.

Kind regards,
Christian
