### ISSUE TITLE
Using correlation id in requests

### ISSUE THREAD

**Issue by WorkAlexGahr** [SAP/cf-nodejs-logging-support#7]
Hi,

when i try to use the library to log complex things in my application log i would love to keep the correlation id. Means one request from express comes in and in the following req/response cycle in want to use the same correlation id for all my logs.

So far i did not see how i can pass the correlation id when i use logger() function.
Thanks
Alex

**Comment by nicklas-dohrn** [comment]
Hi Alex,

we are not quite sure which logger you are refering to.

However, there are only two possibilities:

1. You are currently using one of the middleware approaches (express middleware, restify ...).
    - If you want to write custom messages in the context of your request, we already keep track of the correlationId if you use req.logMessage(...).

    - If you want to fire new requests from within the context of one request, you can get the correlationId with req.getCorrelationId. You should append it to your new request as a header called "X-CorrelationID". Please refer to your used server framework on how to access the header.

    - If you want to keep track of the correlationId through multiple server - client transactions, you can append the correlationId (fetched as noted above) to your current res object as a header and reappend it to the next correlating request from your client.

2. You are currently using the winston transport approach.
    - This tool is only able to complete your log with the required metadata to fulfill logstash metrics.
If you want to keep track of requests you need to use the middleware aproach, because we cannot provide all neccessary data for correct request logs with the transport approach.
